# http://localhost:31041/feeds?cat=void

server:
  servlet-path: /system
  port: 31041


rss:
  feed:
    infosys: https://www.infosys.com/index.xml
    investor: https://www.infosys.com/investors.xml
    media: https://www.infosys.com/blog.xml
    blog: https://www.infosys.com/blog.xml
    
