# http://localhost:31031/rssfeed?cat=void

server:
  port: 31031


rss:
  feed:
    infosys: https://www.infosys.com/index.xml
    investor: https://www.infosys.com/investors.xml
    media: https://www.infosys.com/blog.xml
    blog: https://www.infosys.com/blog.xml
    