version: '2'
  
services:
    mongodata:
        image: mongo:3.2
        volumes:
        - /data/db
        entrypoint: /bin/bash
    mongo:
        image: mongo:3.2
        depends_on: 
            - mongodata
        volumes_from:
            - mongodata
        ports:
            - "31051:31051"
    bootmongo:
        image: r82anand/bootmongo
        depends_on: 
            - mongo
        environment:
            - MONGODB_DB_NAME=feeds
        ports:
            - "31041:31041"
        links:
            - mongo
    bootrest    :
        image: r82anand/bootrest
        depends_on: 
            - bootmongo
        ports:
            - "31031:31031"
    bootchron:
        image: r82anand/bootchron
        depends_on: 
            - bootrest
            - bootmongo
            - mongo
        ports : - "31011:31011"
	app.blogpost.client:
		image: mail2sanu/app.blogpost.client
		depends_on:
			- bootrest
			- bootmongo
			- mongo
		ports: -"31015:31015"